export { default as Intro } from './01_Intro/Intro'
export { default as Img } from './02_Img/Img'
export { default as Reliable } from './03_Reliable/Reliable'
export { default as Rata } from './04_Rata/Rata'
export { default as JuneHeroes } from './05_JuneHeroes/JuneHeroes'
export { default as FightForSeries } from './06_FightForSeries/FightForSeries'
export { default as Lavochkin } from './07_Lavochkin/Lavochkin'
export { default as Lagg3 } from './08_Lagg3/Lagg3'
export { default as Powerful } from './09_Powerful/Powerful'
export { default as Front } from './10_Front/Front'
export { default as La5 } from './11_La5/La5.jsx'
export { default as RecordFlow } from './12_RecordFlow/RecordFlow'
export { default as Agadzhanov } from './13_Agadzhanov/Agadzhanov.jsx'
export { default as FriendlyGuys } from './14_ FriendlyGuys/FriendlyGuys'
export { default as La7 } from './15_La7/La7'
export { default as AfterWar } from './16_AfterWar/AfterWar'
