name: Node CI environment

on: push

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: yarn lint

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

      - name: Run Stylelint
        run: yarn stylelint
